from django.urls import path
from . import views

from django.views.generic import TemplateView

urlpatterns = [
    path('', views.index, name='root_path'),
    path('create_event/', views.create_event, name='create_event'),
    path('calendar/', views.calendar, name='calendar'),
    path('create_sub_draft/', views.create_subscription_draft_view, name='create_sub_draft'),
    path('add_line_item_to_sub_draft/', views.add_line_item_view, name='add_line_item_to_sub_draft'),
    path('view_draft_sub/', views.view_draft_view, name='add_line_item_to_sub_draft'),
    path('commit_draft_sub/', views.commit_draft_view, name='commit_draft_sub'),
    path('add_sell_plan/', views.add_subscription_plan_view, name='add_sell_plan'),
    path('view_sell_plan/', views.view_subscription_plan_view, name='view_sell_plan'),
    path('view_sub_contracts/', views.view_all_subscription_contracts, name='view_sub_contracts'),
    path('change_sub_contracts_line/', views.subscription_contract_product_change_view, name='change_sub_contracts_line'),
    path('renew_sub_contract/', views.create_subscription_billing_attempt_view, name='renew_sub_contract'),
    path('view_billing_attempt/', views.view_subscription_billing_attempt_view, name='view_billing_attempt'),
    path('order_created/', views.order_payment_view, name='order_payment'), #webhook/order_payment
    path('view_customer/', views.view_customer, name='view_customer'),
    path('view_customer_subscriptions/', views.view_customer_subscription, name='view_customer_subscriptions'),
    path('set_sub_contract_next_billing/', views.set_next_billing_date_view, name='set_sub_contract_next_billing'),
    path('view_sub_contract_billing_cycle/', views.view_subscription_billing_cycles, name='view_sub_contract_billing_cycle'),
    path('view_product/', views.view_product_details, name='view_product'),
    path('add_product_meta_field/', views.add_metafield_view, name='add_product_meta_field'),
    path('update_product_meta_field/', views.update_metafield_view, name='update_product_meta_field'),
    path('view_sub_lines/', views.view_subscription_lines, name='view_sub_lines'),
    path('view_product_variant/', views.view_product_variant, name='view_product_variant'),
    path('clear_customer_calendar/', views.clear_customer_calendar, name='clear_customer_calendar'),
    path('get_sub_customer/', views.get_sub_customer_view, name='get_sub_customer'),
    path('update_sub_product_via_calendar/', views.update_sub_product_via_calendar_view, name='update_sub_product_via_calendar'),
    path('expire_sub_contract/', views.expire_subscription_contract_view, name='expire_sub_contract'),
    path('add_customer_metafield/', views.add_metafield_cusomter_view, name='add_customer_metafield'),
    path('update_customer_metafield/', views.update_customer_metafield_view, name='update_customer_metafield'),
    path('get_customer_metafield/', views.get_customer_metafield_view, name='get_customer_metafield'),
    path('get_customer_metafield_specific/', views.get_customer_specific_metafield_view, name='get_customer_metafield_specific'),
    path('create_webhook/', views.create_webhook_view, name='create_webhook'),
    path('cart_check/', views.cart_check_view, name='cart_check'),
    path('proxyapp/', views.shopify_proxy, name='shopify_proxy'),
    path('test/', views.embed_overview, name="test"),
    path('embed/customer/<int:customer_id>/', views.embed_customer, name="embed_customer"),
    path('embed/update-customer-deets/<int:customer_id>/', views.embed_update_customer_deets, name="embed_update_customer_deets"),
    path('embed/remove-customer-product-calendar/<int:customer_id>/<int:product_id>/<str:event_date>/', views.embed_remove_customer_product_calendar, name="embed_remove_customer_product_calendar"),
    path('embed/update-customer-product-calendar/<int:customer_id>/<int:product_id>/<str:event_date>/', views.embed_update_customer_product_calendar, name="embed_update_customer_product_calendar"),
    path('embed/add-customer-product-calendar/<int:customer_id>/', views.embed_add_customer_product_calendar, name="embed_add_customer_product_calendar"),
    path('embed/update-customer-contact-info/<int:customer_id>/', views.embed_update_customer_contact_info, name="embed_update_customer_contact_info"),
    path('embed/calendars/', views.embed_calendars, name="embed_calendars"),
    path('embed/customer-calendars/<int:customer_id>/', views.embed_customer_calendars, name="embed_customer_calendars"),
    path('embed/subscription/<int:subsrciption_id>/', views.embed_subscription, name="embed_subscription"),
    path('embed/cancel_subscription/<int:subsrciption_id>/', views.embed_cancel_sub, name="embed_cancel_subscription"),
    path('embed/skip_subscription/<int:subsrciption_id>/<int:customer_id>/', views.embed_skip_sub_month, name="embed_skip_subscription"),
    path('embed/renew_subscription/<int:subsrciption_id>/', views.embed_renew_subscription, name="embed_renew_subscription"),
    path('embed/subscriptions/', views.embed_subscriptions, name="embed_subscriptions"),
    path('test/subscriptions/', views.embed_subscriptions, name="embed_subscriptions"),
    path('embed/customers/', views.test, name="embed_customers"),
    path('embed/change_subscription_product/<int:subsrciption_id>/<str:lineID>/', views.embed_change_subscription_product, name="embed_change_subscription_product"),
    path('embed/add_subscription_product/<int:subsrciption_id>/', views.embed_add_subscription_product, name="embed_add_subscription_product"),
    path('embed/remove_subscription_product/<int:subsrciption_id>/<str:lineID>/', views.embed_remove_subscription_product, name="embed_remove_subscription_product"),
    path('customer_payment/<int:customer_id>/', views.customer_payment_view, name="customer_payment"),
    path('view_webhooks/', views.view_webhooks, name="view_webhook"),
    path('details/', views.get_details, name="details"),
    path('plan_test/', views.create_plan_view, name="details"),
    path('add_product_sub_group/', views.add_product_to_selling_group_view, name="add_produc_sub_group"),
    path('delete_webhook/<int:webhook_id>/', views.delete_webhook, name="webhook_delete"),
    path('subscription_created/', views.deal_with_subscription_creation, name="subscription_created"),
    path('subscription_renewed/', views.deal_with_subscription_renewal, name="subscription_created"),
    path('view_functions/', views.view_functions, name="view_functions"),
    path('add_function/<str:function_id>/', views.add_functions, name="add_function"),
    path('view_selling_plans/', views.view_selling_plan_groups, name="view_selling_plans"),
    path('update_sub_price/', views.update_product_sub_price, name="update_sub_price"),
    path('delete_selling_plan/', views.delete_selling_plan_view, name="delete_selling_plan"),
    path('view_all_selling_plans/', views.view_all_selling_plans, name="view_all_selling_plans"),
    path('delete_selling_plan_group/<int:selling_plan_group_id>/', views.delete_selling_plan_group_view, name="delete_selling_plan_group"),
    path('all_sub_vars/', views.all_sub_products, name="all_sub_products"),
    path('failed_payment/', views.handle_failure, name="failed_payment")
    
   
]
