# Generated by Django 5.0.3 on 2024-05-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_product_id', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('shopify_customer_id', models.CharField(max_length=100)),
                ('shopify_shop_domain', models.CharField(max_length=255)),
            ],
        ),
    ]
